import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import TopBar from "@/components/shared/top-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Levi | Live selling for your e-commerce platforms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "flex min-h-full flex-col bg-black dark:bg-white"}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="overflow-x-hidden">
            <TopBar />
            <div className="bg-background rounded-[40px] border">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
